apiVersion: batch/v1
kind: Job
metadata:
  name: kube-power
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: kube-power
      containers:
      - name: kube-power
        image: ghcr.io/ianunruh/kube-power
        args:
        - suspend
        - --dry-run
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 256Mi
