apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
commonLabels:
  app.kubernetes.io/name: kube-power
resources:
- ../base
- job.yaml
images:
- name: ghcr.io/ianunruh/kube-power
  newTag: v1.0.1
