namespace: kube-system

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: kube-power

resources:
  - ../base
  - job.yaml

images:
  - name: ghcr.io/ianunruh/kube-power
    newTag: v1.0.1
