kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-power
rules:
- apiGroups: [appsv1]
  resources: [deployments]
  verbs: [get, list, watch, update]
- apiGroups: [appsv1]
  resources: [statefulsets]
  verbs: [get, list, watch, update]
- apiGroups: [batchv1]
  resources: [cronjobs]
  verbs: [get, list, watch, update]
- apiGroups: ['']
  resources: [persistentvolumeclaims]
  verbs: [get, list, watch]
- apiGroups: ['']
  resources: [persistentvolumes]
  verbs: [get, list, watch]
- apiGroups: ['']
  resources: [pods]
  verbs: [get, list, watch]
