apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
commonLabels:
  app.kubernetes.io/name: kube-power
resources:
- clusterrole.yaml
- clusterrolebinding.yaml
- serviceaccount.yaml
- workflowtemplate.yaml
