kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-power
rules:
- apiGroups: [apps]
  resources: [deployments]
  verbs: [get, list, watch, update]
- apiGroups: [apps]
  resources: [statefulsets]
  verbs: [get, list, watch, update]
- apiGroups: [batch]
  resources: [cronjobs]
  verbs: [get, list, watch, update]
- apiGroups: ['']
  resources: [persistentvolumeclaims]
  verbs: [get, list, watch]
- apiGroups: ['']
  resources: [persistentvolumes]
  verbs: [get, list, watch]
- apiGroups: ['']
  resources: [pods]
  verbs: [get, list, watch]
- apiGroups: ['']
  resources: [pods/exec]
  verbs: [create]
- apiGroups: [ceph.rook.io]
  resources: [cephclusters]
  verbs: [get]
